# Generated by Django 3.2.10 on 2023-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_items_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Product_name',
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('Patient_name',), 'verbose_name_plural': 'Items'},
        ),
        migrations.RenameField(
            model_name='items',
            old_name='description',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='Patient_name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Category',
            new_name='Product_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.AddField(
            model_name='items',
            name='Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Product_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Rent_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Rent_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Vendor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
