# Generated by Django 3.2.6 on 2023-04-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_items_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_name',
            options={'ordering': ('name',), 'verbose_name_plural': 'Products'},
        ),
    ]
