# Generated by Django 3.2.6 on 2023-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20230430_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('name',), 'verbose_name_plural': 'Technician'},
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
