# Generated by Django 3.2.6 on 2023-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20230501_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
