# Generated by Django 3.2.6 on 2023-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_items_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('Patient_name',), 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
