# Generated by Django 3.2.6 on 2023-05-28 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20230528_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_code',
            name='Choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.product_name'),
        ),
    ]
