# Generated by Django 3.2.6 on 2023-05-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_alter_items_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_name',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_name',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='Product_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Product_code',
        ),
    ]
