# Generated by Django 3.2.6 on 2023-05-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20230528_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_name',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_name',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='Product_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product_name')),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='Product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.product_code'),
        ),
    ]
