# Generated by Django 3.2.6 on 2023-05-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20230528_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_code',
            old_name='country',
            new_name='Product_name',
        ),
    ]
