# Generated by Django 3.2.10 on 2023-06-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_rename_country_product_code_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_code',
            options={'ordering': ('name',), 'verbose_name_plural': 'Serial no.'},
        ),
        migrations.AddField(
            model_name='product_code',
            name='rent',
            field=models.BooleanField(default=False, verbose_name='rent'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.product_code', verbose_name='Serial no.'),
        ),
    ]
