# Generated by Django 3.2.10 on 2023-06-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20230601_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_code',
            name='rent',
        ),
    ]
