# Generated by Django 3.2.6 on 2023-06-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_items_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('id',), 'verbose_name_plural': 'Patients '},
        ),
    ]
